// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAccordionFields {
  /** title */
  title?: string | undefined;

  /** Accordion Items */
  accordionItems?:
    | (ICarousel | ILayout | IMessage | IPlaylist | ISchedule)[]
    | undefined;
}

/** General purpose accordion */

export interface IAccordion extends Entry<IAccordionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "accordion";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAmazonPodcastFields {
  /** Podcast Image */
  podcastImage?: Record<string, any> | undefined;

  /** Title */
  title: string;

  /** Description */
  description: string;

  /** date */
  date?: string | undefined;

  /** Amazon URL */
  amazonUrl: string;

  /** show */
  show?: IShows | undefined;

  /** slug */
  slug?: string | undefined;
}

export interface IAmazonPodcast extends Entry<IAmazonPodcastFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "amazonPodcast";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBannerFields {
  /** Image */
  heroImage?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Sub Title */
  subTitle?: string | undefined;

  /** Video */
  video?: IVideo | undefined;

  /** Button */
  button?: INavigationLink | undefined;

  /** Button Text */
  buttonText?: string | undefined;

  /** Banner link */
  bannerLink?: string | undefined;

  /** CTA Layout */
  ctaLayout?: ILayout | undefined;
}

export interface IBanner extends Entry<IBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "banner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICarouselFields {
  /** Title */
  title?: string | undefined;

  /** Banners */
  banners: IBanner[];
}

/** A generic carousel to take banners */

export interface ICarousel extends Entry<ICarouselFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "carousel";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICollectionFields {
  /** Title */
  title: string;

  /** Introduction */
  introduction?: string | undefined;

  /** Collection Items */
  collectionItems?:
    | (
        | IBanner
        | IBlog
        | IEvents
        | IMessage
        | IPartner
        | IPodcast
        | IService
        | IShows
        | IStaff
        | IStream
        | IVideo
      )[]
    | undefined;

  /** Type */
  type?:
    | "Podcasts"
    | "Carousel"
    | "Tabs"
    | "Staff"
    | "Sponsors"
    | "Messages"
    | undefined;
}

export interface ICollection extends Entry<ICollectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "collection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IColorFields {
  /** Color name */
  colorName?: string | undefined;

  /** Hex */
  hex?: string | undefined;
}

export interface IColor extends Entry<IColorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "color";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IConfigFields {
  /** Title */
  title: string;

  /** Base URL */
  path_prefix: string;

  /** Site Production Url */
  siteProductionUrl: string;

  /** Site description */
  description?: string | undefined;

  /** Header configuration */
  header?: IHeader | undefined;

  /** Footer configuration */
  footer?: IFooter | undefined;
}

export interface IConfig extends Entry<IConfigFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "config";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFooterFields {
  /** Title */
  title?: string | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Social links */
  social_links?: ILinkedIcon[] | undefined;

  /** Quick Links */
  quickLInks?: INavigationLink[] | undefined;

  /** Copyright */
  copyright?: string | undefined;

  /** Right Column */
  rightColumn?: IMessage | undefined;
}

export interface IFooter extends Entry<IFooterFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "footer";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeaderConfigurationFields {
  /** Title */
  title?: string | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Alert */
  alert?: string | undefined;

  /** Main Menu */
  mainMenu?: IMenu | undefined;

  /** Secondary Menu */
  secondaryMenu?: IMenu | undefined;

  /** Call to action */
  callToAction?: IMessage | undefined;
}

export interface IHeaderConfiguration
  extends Entry<IHeaderConfigurationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "headerConfiguration";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHtmlBlockFields {
  /** Title */
  title?: string | undefined;

  /** HTML */
  html?: Document | undefined;
}

export interface IHtmlBlock extends Entry<IHtmlBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "htmlBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IIntroductionAndContentFields {
  /** Title */
  title?: string | undefined;
}

export interface IIntroductionAndContent
  extends Entry<IIntroductionAndContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "introductionAndContent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILandingPageFields {
  /** Image */
  image: Asset;

  /** Show Banner */
  showBanner?: boolean | undefined;

  /** Title */
  title?: string | undefined;

  /** Te reo title */
  teReoTitle?: string | undefined;

  /** introduction */
  introduction: string;

  /** content */
  content?: Document | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** Components */
  components?:
    | (
        | IAccordion
        | ICarousel
        | IIntroductionAndContent
        | ILayout
        | IPlaylist
        | IPlaylistGrid
        | IQueryStringPlaylist
        | ISchedule
        | IShowsOnToday
        | ISponsorsList
        | IStaffList
        | IShowList
      )[]
    | undefined;
}

/** A landing page */

export interface ILandingPage extends Entry<ILandingPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "landingPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILayoutFields {
  /** title */
  title: string;

  /** Columns */
  columns?: ILayoutColum[] | undefined;

  /** Show Layout Title */
  showLayoutTitle: boolean;
}

export interface ILayout extends Entry<ILayoutFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "layout";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILayoutColumFields {
  /** Title */
  title?: string | undefined;

  /** Layout component */
  layoutComponent?:
    | (
        | IAccordion
        | IMessage
        | IPlaylist
        | IPlaylistGrid
        | ISchedule
        | ISearchBox
        | IShows
        | IShowsOnToday
        | ISponsorsList
        | IStaff
        | IStream
        | IShowList
      )[]
    | undefined;

  /** Bootstrap Width */
  bootstrapWidth:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12";

  /** Offset */
  offset?: number | undefined;
}

export interface ILayoutColum extends Entry<ILayoutColumFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "layoutColum";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILinkedIconFields {
  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Font Awesome Classes */
  fontAwesomeClasses?: string | undefined;

  /** Link */
  link?: string | undefined;
}

export interface ILinkedIcon extends Entry<ILinkedIconFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "linkedIcon";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMenuFields {
  /** Title */
  title?: string | undefined;

  /** logo */
  logo?: Asset | undefined;

  /** Links */
  links?: INavigationLink[] | undefined;

  /** Featured Button */
  featuredButton?: IMessage | undefined;
}

/** A collection of Page links or Navigation Links if nesting is required */

export interface IMenu extends Entry<IMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "menu";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMessageFields {
  /** title */
  title?: string | undefined;

  /** Headline */
  headline?: string | undefined;

  /** Overview */
  overview?: Document | undefined;

  /** LinkText */
  linkText?: string | undefined;

  /** Link Url */
  linkUrl?: string | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Background color */
  backgroundColor?: IColor | undefined;

  /** Icon Class */
  iconClass?: string | undefined;
}

/** A generic block with a headline, overview   image and internal link */

export interface IMessage extends Entry<IMessageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "message";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMetatagsFields {
  /** Internal Name */
  internalName: string;

  /** Meta Title */
  metaTitle?: string | undefined;

  /** Meta Description */
  metaDescription?: string | undefined;

  /** Canonical Url */
  canonicalUrl?: string | undefined;

  /** No Follow */
  noFollow?: boolean | undefined;

  /** No Index */
  noIndex?: boolean | undefined;
}

/** A collection of meta data fields - generally used for content intended for web distribution, i.e. "Page" types.  */

export interface IMetatags extends Entry<IMetatagsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "metatags";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INavigationLinkFields {
  /** Link Text */
  linkText?: string | undefined;

  /** Internal Link */
  internalLink: ILandingPage | IPodcast | IShows;

  /** Sublinks */
  sublinks?: INavigationLink[] | undefined;
}

/** An internal or external link enabling nested sub menu items */

export interface INavigationLink extends Entry<INavigationLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "navigationLink";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPartnerFields {
  /** Title */
  title: string;

  /** Logo */
  logo: Asset;

  /** Introduction */
  introduction: string;

  /** Content */
  content: Document;

  /** URL */
  url?: string | undefined;

  /** Related Content */
  relatedContent?: (IBlog | ICaseStudy | INews)[] | undefined;

  /** slug */
  slug?: string | undefined;

  /** SEO */
  seo?: IMetatags | undefined;

  /** path */
  path?: string | undefined;
}

export interface IPartner extends Entry<IPartnerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "partner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPlaylistFields {
  /** Show title */
  showTitle?: boolean | undefined;

  /** Title */
  title: string;

  /** description */
  description?: string | undefined;

  /** URL */
  url: string;

  /** height */
  height: number;

  /** Hide visual player */
  hideVisualPlayer?: boolean | undefined;

  /** Archived Show */
  archivedShow?: boolean | undefined;
}

/** An embedded playlist */

export interface IPlaylist extends Entry<IPlaylistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "playlist";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPlaylistGridFields {
  /** Show Title */
  showTitle?: boolean | undefined;

  /** Title */
  title?: string | undefined;

  /** Playlist Items */
  playlistItems?: IPlaylist[] | undefined;

  /** Row Height */
  rowHeight?: number | undefined;

  /** Column Bootstrap Width */
  columnBootstrapWidth?: number | undefined;

  /** Show Visual Player */
  showVisualPlayer?: boolean | undefined;
}

export interface IPlaylistGrid extends Entry<IPlaylistGridFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "playlistGrid";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IQueryStringPlaylistFields {
  /** Title */
  title?: string | undefined;

  /** height */
  height?: number | undefined;
}

/** A playlist renderer that gets the playlist id from the querystring */

export interface IQueryStringPlaylist
  extends Entry<IQueryStringPlaylistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "queryStringPlaylist";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IScheduleFields {
  /** Show today only */
  showTodayOnly?: boolean | undefined;

  /** Title */
  title: string;

  /** Monday */
  monday?: IShows[] | undefined;

  /** Tuesday */
  tuesday?: IShows[] | undefined;

  /** Wednesday */
  wednesday?: IShows[] | undefined;

  /** Thursday */
  thursday?: IShows[] | undefined;

  /** Friday */
  friday?: IShows[] | undefined;

  /** Saturday */
  saturday?: IShows[] | undefined;

  /** Sunday */
  sunday?: IShows[] | undefined;
}

/** A collection of shows */

export interface ISchedule extends Entry<IScheduleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "schedule";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISearchBoxFields {
  /** Title */
  title?: string | undefined;
}

export interface ISearchBox extends Entry<ISearchBoxFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "searchBox";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IServiceFields {
  /** Title */
  title?: string | undefined;

  /** Services Image */
  servicesImage?: Asset | undefined;

  /** Post Content */
  postContent?: IPost | undefined;

  /** Related Content */
  relatedContent?: (IBlog | INews)[] | undefined;

  /** SEO */
  seo?: IMetatags | undefined;

  /** Icon Class */
  iconClass?: string | undefined;

  /** slug */
  slug?: string | undefined;

  /** Service Collection */
  serviceCollection?: boolean | undefined;

  /** Related Services */
  relatedServices?: IService[] | undefined;
}

/** A service page */

export interface IService extends Entry<IServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "service";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowListFields {
  /** Title */
  title?: string | undefined;

  /** Shows */
  shows?: IShows[] | undefined;
}

export interface IShowList extends Entry<IShowListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "showList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowsFields {
  /** image */
  image?: Asset | undefined;

  /** Show Banner */
  showBanner?: boolean | undefined;

  /** Archived */
  archived?: boolean | undefined;

  /** Title */
  title: string;

  /** introduction */
  introduction: string;

  /** content */
  content?: Document | undefined;

  /** Time Slots */
  timeSlots?: IShowSlot[] | undefined;

  /** Show URL */
  showUrl?: string | undefined;

  /** playlistUrl */
  playlistUrl?: string | undefined;

  /** DJ */
  dj: IStaff[];

  /** tags */
  tags?: ITag[] | undefined;

  /** Components */
  components?:
    | (
        | IAccordion
        | IIntroductionAndContent
        | IPlaylist
        | ISchedule
        | IStream
        | IVideo
      )[]
    | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** Sponsor */
  sponsor?: ISponsor | undefined;
}

/** Scheduled radio shows for Waiheke Radio */

export interface IShows extends Entry<IShowsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "shows";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowSlotFields {
  /** Title */
  title?: string | undefined;

  /** Day */
  day:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday";

  /** Start Time */
  startTime: string;

  /** End Time */
  endTime: string;

  /** AM PM */
  amPm?: "AM" | "PM" | undefined;
}

/** A day / time range object for show scheduling */

export interface IShowSlot extends Entry<IShowSlotFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "showSlot";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowsOnTodayFields {
  /** Title */
  title?: string | undefined;

  /** Schedule */
  schedule?: ISchedule | undefined;
}

export interface IShowsOnToday extends Entry<IShowsOnTodayFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "showsOnToday";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISponsorFields {
  /** image */
  image?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Description */
  description?: Document | undefined;
}

export interface ISponsor extends Entry<ISponsorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sponsor";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISponsorsListFields {
  /** Title */
  title?: string | undefined;

  /** Sponsors */
  sponsors?: ISponsor[] | undefined;
}

export interface ISponsorsList extends Entry<ISponsorsListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sponsorsList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStaffFields {
  /** Title */
  title?: string | undefined;

  /** Photo */
  photo?: Asset | undefined;

  /** ShortBio */
  shortBio: string;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** content */
  content?: Document | undefined;
}

/** An entity to contain staff and authors */

export interface IStaff extends Entry<IStaffFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "staff";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStaffListFields {
  /** Title */
  title?: string | undefined;

  /** Staff */
  staff?: IStaff[] | undefined;
}

export interface IStaffList extends Entry<IStaffListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "staffList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStreamFields {
  /** Title */
  title: string;

  /** url */
  url: string;

  /** Playing Now */
  playingNow?: string | undefined;
}

export interface IStream extends Entry<IStreamFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "stream";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagFields {
  /** Tag Name */
  tagName: string;
}

/** A single field tag item for categorisation */

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tag";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** Image */
  image?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Watch Message */
  watchMessage?: string | undefined;

  /** Youtube ID */
  youtubeId?: string | undefined;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "accordion"
  | "amazonPodcast"
  | "banner"
  | "carousel"
  | "collection"
  | "color"
  | "config"
  | "footer"
  | "headerConfiguration"
  | "htmlBlock"
  | "introductionAndContent"
  | "landingPage"
  | "layout"
  | "layoutColum"
  | "linkedIcon"
  | "menu"
  | "message"
  | "metatags"
  | "navigationLink"
  | "partner"
  | "playlist"
  | "playlistGrid"
  | "queryStringPlaylist"
  | "schedule"
  | "searchBox"
  | "service"
  | "showList"
  | "shows"
  | "showSlot"
  | "showsOnToday"
  | "sponsor"
  | "sponsorsList"
  | "staff"
  | "staffList"
  | "stream"
  | "tag"
  | "video";

export type IEntry =
  | IAccordion
  | IAmazonPodcast
  | IBanner
  | ICarousel
  | ICollection
  | IColor
  | IConfig
  | IFooter
  | IHeaderConfiguration
  | IHtmlBlock
  | IIntroductionAndContent
  | ILandingPage
  | ILayout
  | ILayoutColum
  | ILinkedIcon
  | IMenu
  | IMessage
  | IMetatags
  | INavigationLink
  | IPartner
  | IPlaylist
  | IPlaylistGrid
  | IQueryStringPlaylist
  | ISchedule
  | ISearchBox
  | IService
  | IShowList
  | IShows
  | IShowSlot
  | IShowsOnToday
  | ISponsor
  | ISponsorsList
  | IStaff
  | IStaffList
  | IStream
  | ITag
  | IVideo;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
