// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAccordionFields {
  /** title */
  title?: string | undefined;

  /** Accordion Items */
  accordionItems?:
    | (
        | ICarousel
        | ILayout
        | IMessage
        | IPlaylist
        | ISchedule
        | IAmazonPodcast
        | IAmazonPlaylist
        | IFilteredAmazonPlaylist
      )[]
    | undefined;
}

/** General purpose accordion */

export interface IAccordion extends Entry<IAccordionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "accordion";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAmazonPlaylistFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Podcasts */
  podcasts: IAmazonPodcast[];

  /** Pagination */
  pagination?: boolean | undefined;

  /** Count Per Page */
  countPerPage?: number | undefined;

  /** Sorting */
  sorting?: boolean | undefined;
}

export interface IAmazonPlaylist extends Entry<IAmazonPlaylistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "amazonPlaylist";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAmazonPodcastFields {
  /** Podcast Image */
  podcastImage: Record<string, any>;

  /** Title */
  title: string;

  /** Description */
  description: string;

  /** date */
  date: string;

  /** Amazon URL */
  amazonUrl: string;

  /** show */
  show: IShows;

  /** slug */
  slug?: string | undefined;
}

export interface IAmazonPodcast extends Entry<IAmazonPodcastFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "amazonPodcast";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBannerFields {
  /** Banner Image */
  bannerImage?: Record<string, any> | undefined;

  /** Image */
  heroImage?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Sub Title */
  subTitle?: string | undefined;

  /** Video */
  video?: IVideo | undefined;

  /** Button */
  button?: INavigationLink | undefined;

  /** Button Text */
  buttonText?: string | undefined;

  /** Banner link */
  bannerLink?: string | undefined;

  /** CTA Layout */
  ctaLayout?: ILayout | undefined;
}

export interface IBanner extends Entry<IBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "banner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IConfigFields {
  /** Title */
  title: string;

  /** Base URL */
  path_prefix: string;

  /** Site Production Url */
  siteProductionUrl: string;

  /** Site description */
  description?: string | undefined;

  /** Header configuration */
  header?: IHeader | undefined;

  /** Footer configuration */
  footer?: IFooter | undefined;
}

export interface IConfig extends Entry<IConfigFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "config";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFilteredAmazonPlaylistFields {
  /** Title */
  title: string;

  /** Show Name */
  showName?: string | undefined;

  /** Title Contains */
  titleContains?: string | undefined;

  /** Description Contains */
  descriptionContains?: string | undefined;

  /** Start Date */
  startDate?: string | undefined;

  /** End Date */
  endDate?: string | undefined;

  /** Show */
  show?: IShows | undefined;

  /** Pagination */
  pagination?: boolean;

  /** Count per page */
  countPerPage?: number;

  /** Sorting */
  sorting?: boolean;
}

export interface IFilteredAmazonPlaylist
  extends Entry<IFilteredAmazonPlaylistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "filteredAmazonPlaylist";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFooterFields {
  /** Title */
  title?: string | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Social links */
  social_links?: ILinkedIcon[] | undefined;

  /** Quick Links */
  quickLInks?: INavigationLink[] | undefined;

  /** Copyright */
  copyright?: string | undefined;

  /** Right Column */
  rightColumn?: IMessage | undefined;
}

export interface IFooter extends Entry<IFooterFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "footer";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeaderConfigurationFields {
  /** Title */
  title?: string | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Alert */
  alert?: string | undefined;

  /** Main Menu */
  mainMenu?: IMenu | undefined;

  /** Secondary Menu */
  secondaryMenu?: IMenu | undefined;

  /** Call to action */
  callToAction?: IMessage | undefined;
}

export interface IHeaderConfiguration
  extends Entry<IHeaderConfigurationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "headerConfiguration";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IIntroductionAndContentFields {
  /** Title */
  title?: string | undefined;
}

export interface IIntroductionAndContent
  extends Entry<IIntroductionAndContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "introductionAndContent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILandingPageFields {
  /** Title */
  title?: string | undefined;

  /** Cloudinary Image */
  cloudinaryImage: Record<string, any>;

  /** Show Introduction */
  showIntroduction?: boolean | undefined;

  /** Show Content */
  showContent?: boolean | undefined;

  /** Show Banner */
  showBanner?: boolean | undefined;

  /** Te reo title */
  teReoTitle?: string | undefined;

  /** introduction */
  introduction: string;

  /** content */
  content?: Document | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** Components */
  components?:
    | (
        | IAccordion
        | ICarousel
        | IIntroductionAndContent
        | ILayout
        | IPlaylist
        | IPlaylistGrid
        | IQueryStringPlaylist
        | ISchedule
        | IShowsOnToday
        | ISponsorsList
        | IStaffList
        | IAmazonPlaylist
        | ILatestPodcasts
        | ISearchBox
        | IArchivedShows
        | IFilteredAmazonPlaylist
        | ICurrentShows
        | IHtmlBlock
        | IList
      )[]
    | undefined;

  /** Image */
  image: Asset;
}

/** A landing page */

export interface ILandingPage extends Entry<ILandingPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "landingPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILatestPodcastsFields {
  /** Title */
  title: string;

  /** Filter by Show */
  filterByShow?: IShows | undefined;

  /** Number to show */
  numberToShow: number;

  /** Show title */
  showTitle: boolean;

  /** Pagination */
  pagination?: boolean;

  /** Count per page */
  countPerPage?: number;

  /** Show sorting */
  showSorting?: boolean;
}

export interface ILatestPodcasts extends Entry<ILatestPodcastsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "latestPodcasts";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILayoutFields {
  /** title */
  title: string;

  /** Columns */
  columns?: ILayoutColum[] | undefined;

  /** Show Layout Title */
  showLayoutTitle: boolean;
}

export interface ILayout extends Entry<ILayoutFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "layout";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILayoutColumFields {
  /** Title */
  title?: string | undefined;

  /** Layout component */
  layoutComponent?:
    | (
        | IAccordion
        | IMessage
        | IPlaylist
        | IPlaylistGrid
        | ISchedule
        | ISearchBox
        | IShows
        | IShowsOnToday
        | ISponsorsList
        | IStaff
        | IStream
        | IShowList
        | IAmazonPlaylist
        | IAmazonPodcast
        | ILatestPodcasts
        | IList
      )[]
    | undefined;

  /** Bootstrap Width */
  bootstrapWidth:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12";

  /** Offset */
  offset?: number | undefined;
}

export interface ILayoutColum extends Entry<ILayoutColumFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "layoutColum";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILinkedIconFields {
  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Font Awesome Classes */
  fontAwesomeClasses?: string | undefined;

  /** Link */
  link?: string | undefined;
}

export interface ILinkedIcon extends Entry<ILinkedIconFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "linkedIcon";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IListFields {
  /** Title */
  title: string;

  /** Type */
  type?:
    | "Staff List"
    | "Show List"
    | "Sponsor List"
    | "Stream List"
    | "Banner List"
    | undefined;

  /** Show Status */
  showStatus?: "Current" | "Archived" | "All" | "Show on Today" | undefined;

  /** Show Schedule */
  showSchedule?: ISchedule | undefined;

  /** Staff Status */
  staffStatus?: "Current" | "Previous" | "All" | undefined;

  /** Banners */
  banners?: IBanner[] | undefined;
}

export interface IList extends Entry<IListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "list";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMenuFields {
  /** Title */
  title?: string | undefined;

  /** logo */
  logo?: Asset | undefined;

  /** Links */
  links?: INavigationLink[] | undefined;

  /** Featured Button */
  featuredButton?: IMessage | undefined;
}

/** A collection of Page links or Navigation Links if nesting is required */

export interface IMenu extends Entry<IMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "menu";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMessageFields {
  /** title */
  title?: string | undefined;

  /** Headline */
  headline?: string | undefined;

  /** Overview */
  overview?: Document | undefined;

  /** LinkText */
  linkText?: string | undefined;

  /** Link Url */
  linkUrl?: string | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Icon Class */
  iconClass?: string | undefined;
}

/** A generic block with a headline, overview   image and internal link */

export interface IMessage extends Entry<IMessageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "message";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INavigationLinkFields {
  /** Link Text */
  linkText?: string | undefined;

  /** Internal Link */
  internalLink: ILandingPage | IPodcast | IShows;

  /** Sublinks */
  sublinks?: INavigationLink[] | undefined;
}

/** An internal or external link enabling nested sub menu items */

export interface INavigationLink extends Entry<INavigationLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "navigationLink";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPlaylistFields {
  /** Show title */
  showTitle?: boolean | undefined;

  /** Title */
  title: string;

  /** description */
  description?: string | undefined;

  /** URL */
  url: string;

  /** height */
  height: number;

  /** Hide visual player */
  hideVisualPlayer?: boolean | undefined;

  /** Archived Show */
  archivedShow?: boolean | undefined;
}

/** An embedded playlist */

export interface IPlaylist extends Entry<IPlaylistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "playlist";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPlaylistGridFields {
  /** Show Title */
  showTitle?: boolean | undefined;

  /** Title */
  title?: string | undefined;

  /** Playlist Items */
  playlistItems?: IPlaylist[] | undefined;

  /** Row Height */
  rowHeight?: number | undefined;

  /** Column Bootstrap Width */
  columnBootstrapWidth?: number | undefined;

  /** Show Visual Player */
  showVisualPlayer?: boolean | undefined;
}

export interface IPlaylistGrid extends Entry<IPlaylistGridFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "playlistGrid";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IQueryStringPlaylistFields {
  /** Title */
  title?: string | undefined;

  /** height */
  height?: number | undefined;
}

/** A playlist renderer that gets the playlist id from the querystring */

export interface IQueryStringPlaylist
  extends Entry<IQueryStringPlaylistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "queryStringPlaylist";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IScheduleFields {
  /** Show today only */
  showTodayOnly?: boolean | undefined;

  /** Title */
  title: string;

  /** Monday */
  monday?: IShows[] | undefined;

  /** Tuesday */
  tuesday?: IShows[] | undefined;

  /** Wednesday */
  wednesday?: IShows[] | undefined;

  /** Thursday */
  thursday?: IShows[] | undefined;

  /** Friday */
  friday?: IShows[] | undefined;

  /** Saturday */
  saturday?: IShows[] | undefined;

  /** Sunday */
  sunday?: IShows[] | undefined;
}

/** A collection of shows */

export interface ISchedule extends Entry<IScheduleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "schedule";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISearchBoxFields {
  /** Title */
  title?: string | undefined;
}

export interface ISearchBox extends Entry<ISearchBoxFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "searchBox";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowsFields {
  /** image */
  image?: Asset | undefined;

  /** cimage */
  cimage: Record<string, any>;

  /** Show Banner */
  showBanner?: boolean | undefined;

  /** Archived */
  archived: boolean;

  /** Title */
  title: string;

  /** introduction */
  introduction: string;

  /** content */
  content?: Document | undefined;

  /** Time Slots */
  timeSlots?: IShowSlot[] | undefined;

  /** Show URL */
  showUrl?: string | undefined;

  /** Playlist URL */
  playlistUrl?: string | undefined;

  /** DJ */
  dj: IStaff[];

  rss?: boolean | undefined;

  /** Chat */
  chat?: boolean | undefined;

  /** Components */
  components?:
    | (
        | IAccordion
        | IIntroductionAndContent
        | IPlaylist
        | ISchedule
        | IStream
        | IVideo
        | IAmazonPlaylist
        | IAmazonPodcast
        | ILatestPodcasts
        | IFilteredAmazonPlaylist
      )[]
    | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** Sponsor */
  sponsor?: ISponsor | undefined;
}

/** Scheduled radio shows for Waiheke Radio */

export interface IShows extends Entry<IShowsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "shows";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowSlotFields {
  /** Title */
  title?: string | undefined;

  /** Day */
  day:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday";

  /** Start Time */
  startTime: string;

  /** End Time */
  endTime: string;

  /** AM PM */
  amPm?: "AM" | "PM" | undefined;
}

/** A day / time range object for show scheduling */

export interface IShowSlot extends Entry<IShowSlotFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "showSlot";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowsOnTodayFields {
  /** Title */
  title?: string | undefined;

  /** Schedule */
  schedule?: ISchedule | undefined;
}

export interface IShowsOnToday extends Entry<IShowsOnTodayFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "showsOnToday";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISponsorFields {
  /** image */
  image?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Description */
  description?: Document | undefined;
}

export interface ISponsor extends Entry<ISponsorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sponsor";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISponsorsListFields {
  /** Title */
  title?: string | undefined;

  /** Sponsors */
  sponsors?: ISponsor[] | undefined;
}

export interface ISponsorsList extends Entry<ISponsorsListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sponsorsList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStaffFields {
  /** headshot */
  headshot: Record<string, any>;

  /** Title */
  title?: string | undefined;

  /** Current DJ */
  currentDj?: boolean | undefined;

  /** Photo */
  photo?: Asset | undefined;

  /** ShortBio */
  shortBio: string;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** content */
  content?: Document | undefined;
}

/** An entity to contain staff and authors */

export interface IStaff extends Entry<IStaffFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "staff";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStreamFields {
  /** Title */
  title: string;

  /** url */
  url: string;

  /** Playing Now */
  playingNow?: string | undefined;
}

export interface IStream extends Entry<IStreamFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "stream";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** Image */
  image?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Watch Message */
  watchMessage?: string | undefined;

  /** Youtube ID */
  youtubeId?: string | undefined;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "accordion"
  | "amazonPlaylist"
  | "amazonPodcast"
  | "banner"
  | "config"
  | "filteredAmazonPlaylist"
  | "footer"
  | "headerConfiguration"
  | "introductionAndContent"
  | "landingPage"
  | "latestPodcasts"
  | "layout"
  | "layoutColum"
  | "linkedIcon"
  | "list"
  | "menu"
  | "message"
  | "navigationLink"
  | "playlist"
  | "playlistGrid"
  | "queryStringPlaylist"
  | "schedule"
  | "searchBox"
  | "shows"
  | "showSlot"
  | "showsOnToday"
  | "sponsor"
  | "sponsorsList"
  | "staff"
  | "stream"
  | "video";

export type IEntry =
  | IAccordion
  | IAmazonPlaylist
  | IAmazonPodcast
  | IBanner
  | IConfig
  | IFilteredAmazonPlaylist
  | IFooter
  | IHeaderConfiguration
  | IIntroductionAndContent
  | ILandingPage
  | ILatestPodcasts
  | ILayout
  | ILayoutColum
  | ILinkedIcon
  | IList
  | IMenu
  | IMessage
  | INavigationLink
  | IPlaylist
  | IPlaylistGrid
  | IQueryStringPlaylist
  | ISchedule
  | ISearchBox
  | IShows
  | IShowSlot
  | IShowsOnToday
  | ISponsor
  | ISponsorsList
  | IStaff
  | IStream
  | IVideo;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
