// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBannerFields {
  /** Image */
  heroImage?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Sub Title */
  subTitle?: string | undefined;

  /** Video */
  video?: IVideo | undefined;

  /** Button */
  button?: IBlog | IEvents | ILandingPage | IPost | undefined;

  /** Button Text */
  buttonText: string;
}

export interface IBanner extends Entry<IBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "banner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogFields {
  /** Title */
  title?: string | undefined;

  /** Author */
  author?: IStaff[] | undefined;

  /** Date */
  date: string;

  /** Post Content */
  postContent: IPost;

  /** Tags */
  tags: ITag[];

  /** SEO */
  seo?: IMetatags | undefined;

  /** slug */
  slug?: string | undefined;

  /** Blocks */
  blocks?:
    | (
        | ICarousel
        | IUiCarouselCards
        | IUiMessageCarousel
        | IUiPartner
        | IUiPeople
        | IUiServices
      )[]
    | undefined;

  /** path */
  path?: string | undefined;
}

export interface IBlog extends Entry<IBlogFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blog";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICollectionFields {
  /** Title */
  title: string;

  /** Introduction */
  introduction?: string | undefined;

  /** Collection Items */
  collectionItems?:
    | (
        | IBanner
        | IBlog
        | IEvents
        | IMessage
        | IPartner
        | IPodcast
        | IService
        | IShows
        | IStaff
        | IStream
        | IVideo
      )[]
    | undefined;

  /** Type */
  type?:
    | "Podcasts"
    | "Carousel"
    | "Tabs"
    | "Staff"
    | "Sponsors"
    | "Messages"
    | undefined;
}

export interface ICollection extends Entry<ICollectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "collection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IColorFields {
  /** Color name */
  colorName?: string | undefined;

  /** Hex */
  hex?: string | undefined;
}

export interface IColor extends Entry<IColorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "color";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComponentFields {
  /** Title */
  title: string;

  /** Single Item */
  singleItem?:
    | IBanner
    | IPodcast
    | ISchedule
    | IShows
    | IStaff
    | IVideo
    | undefined;

  /** Collections */
  collections?: ICollection[] | undefined;
}

export interface IComponent extends Entry<IComponentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "component";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IConfigFields {
  /** Title */
  title: string;

  /** Base URL */
  path_prefix: string;

  /** Site Production Url */
  siteProductionUrl: string;

  /** Site description */
  description?: string | undefined;

  /** Header configuration */
  header?: IHeader | undefined;

  /** Footer configuration */
  footer?: IFooter | undefined;
}

export interface IConfig extends Entry<IConfigFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "config";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEventsFields {
  /** Title */
  title?: string | undefined;

  /** Date */
  date?: string | undefined;

  /** Date Text */
  dateText?: string | undefined;

  /** Time Text */
  timeText?: string | undefined;

  /** Price Text */
  priceText?: string | undefined;

  /** Ticket URL */
  ticketUrl?: string | undefined;

  /** Ticket URL Link Text */
  ticketUrlLinkText?: string | undefined;

  /** Post Content */
  postContent: IPost;

  /** Tags */
  tags: ITag[];

  /** SEO */
  seo?: IMetatags | undefined;

  /** slug */
  slug?: string | undefined;

  /** Blocks */
  blocks?:
    | (
        | ICarousel
        | IUiCarouselCards
        | IUiMessageCarousel
        | IUiPartner
        | IUiPeople
        | IUiServices
      )[]
    | undefined;

  /** path */
  path: string;

  /** Postponed */
  postponed?: boolean | undefined;

  /** SoldOut */
  soldOut?: boolean | undefined;

  /** Free Event */
  freeEvent?: boolean | undefined;

  /** Registration */
  registration?: boolean | undefined;
}

/** Events for Artworks Theatre */

export interface IEvents extends Entry<IEventsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "events";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFooterFields {
  /** Title */
  title?: string | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Social links */
  social_links?: ILinkedIcon[] | undefined;

  /** Quick Links */
  quickLInks?: INavigationLink[] | undefined;

  /** Copyright */
  copyright?: string | undefined;

  /** Right Column */
  rightColumn?: IMessage | undefined;
}

export interface IFooter extends Entry<IFooterFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "footer";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeaderConfigurationFields {
  /** Title */
  title?: string | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Alert */
  alert?: string | undefined;

  /** Main Menu */
  mainMenu?: IMenu | undefined;

  /** Secondary Menu */
  secondaryMenu?: IMenu | undefined;

  /** Call to action */
  callToAction?: IMessage | undefined;
}

export interface IHeaderConfiguration
  extends Entry<IHeaderConfigurationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "headerConfiguration";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILandingPageFields {
  /** Image */
  image?: Asset | undefined;

  /** Show Banner */
  showBanner?: boolean | undefined;

  /** Title */
  title?: string | undefined;

  /** Te reo title */
  teReoTitle?: string | undefined;

  /** introduction */
  introduction?: string | undefined;

  /** content */
  content?: Document | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;

  /** Components */
  components?: IComponent | undefined;
}

/** A landing page */

export interface ILandingPage extends Entry<ILandingPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "landingPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILinkedIconFields {
  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Font Awesome Classes */
  fontAwesomeClasses?: string | undefined;

  /** Link */
  link?: string | undefined;
}

export interface ILinkedIcon extends Entry<ILinkedIconFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "linkedIcon";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMenuFields {
  /** Title */
  title?: string | undefined;

  /** logo */
  logo?: Asset | undefined;

  /** Links */
  links?: INavigationLink[] | undefined;

  /** Featured Button */
  featuredButton?: IMessage | undefined;
}

/** A collection of Page links or Navigation Links if nesting is required */

export interface IMenu extends Entry<IMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "menu";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMessageFields {
  /** Headline */
  headline?: string | undefined;

  /** Overview */
  overview?: Document | undefined;

  /** LinkText */
  linkText?: string | undefined;

  /** Link Url */
  linkUrl?: string | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Background color */
  backgroundColor?: IColor | undefined;

  /** Icon Class */
  iconClass?: string | undefined;
}

/** A generic block with a headline, overview   image and internal link */

export interface IMessage extends Entry<IMessageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "message";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMetatagsFields {
  /** Internal Name */
  internalName: string;

  /** Meta Title */
  metaTitle?: string | undefined;

  /** Meta Description */
  metaDescription?: string | undefined;

  /** Canonical Url */
  canonicalUrl?: string | undefined;

  /** No Follow */
  noFollow?: boolean | undefined;

  /** No Index */
  noIndex?: boolean | undefined;
}

/** A collection of meta data fields - generally used for content intended for web distribution, i.e. "Page" types.  */

export interface IMetatags extends Entry<IMetatagsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "metatags";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INavigationLinkFields {
  /** Link Text */
  linkText?: string | undefined;

  /** External Link */
  externalLink?: string | undefined;

  /** Internal Link */
  internalLink?: ILandingPage | IPodcast | IShows | undefined;

  /** Sublinks */
  sublinks?: INavigationLink[] | undefined;
}

/** An internal or external link enabling nested sub menu items */

export interface INavigationLink extends Entry<INavigationLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "navigationLink";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPartnerFields {
  /** Title */
  title: string;

  /** Logo */
  logo: Asset;

  /** Introduction */
  introduction: string;

  /** Content */
  content: Document;

  /** URL */
  url?: string | undefined;

  /** Related Content */
  relatedContent?: (IBlog | ICaseStudy | INews)[] | undefined;

  /** slug */
  slug?: string | undefined;

  /** SEO */
  seo?: IMetatags | undefined;

  /** path */
  path?: string | undefined;
}

export interface IPartner extends Entry<IPartnerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "partner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPodcastFields {
  /** Title */
  title?: string | undefined;

  /** MP3 Url */
  mp3Url?: string | undefined;

  image?: Asset | undefined;

  /** Post Content */
  postContent: IPost;

  /** Related Show */
  relatedShow?: IShows | undefined;

  /** SEO */
  seo?: IMetatags | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;
}

export interface IPodcast extends Entry<IPodcastFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "podcast";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPostFields {
  /** Featured Image */
  featuredImage: Asset;

  /** Introduction */
  introduction?: string | undefined;

  /** Content */
  content: Document;

  /** Video */
  video?: IVideo | undefined;

  /** Date */
  date: string;

  /** Tags */
  tags?: ITag[] | undefined;
}

/** Base post page */

export interface IPost extends Entry<IPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "post";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IScheduleFields {
  /** Title */

  showTodayOnly: boolean;
  title: string;

  /** Monday */
  monday?: IShows[] | undefined;

  /** Tuesday */
  tuesday?: IShows[] | undefined;

  /** Wednesday */
  wednesday?: IShows[] | undefined;

  /** Thursday */
  thursday?: IShows[] | undefined;

  /** Friday */
  friday?: IShows[] | undefined;

  /** Saturday */
  saturday?: IShows[] | undefined;

  /** Sunday */
  sunday?: IShows[] | undefined;
}

/** A collection of shows */

export interface ISchedule extends Entry<IScheduleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "schedule";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IServiceFields {
  /** Title */
  title?: string | undefined;

  /** Services Image */
  servicesImage?: Asset | undefined;

  /** Post Content */
  postContent?: IPost | undefined;

  /** Related Content */
  relatedContent?: (IBlog | INews)[] | undefined;

  /** SEO */
  seo?: IMetatags | undefined;

  /** Icon Class */
  iconClass?: string | undefined;

  /** slug */
  slug?: string | undefined;

  /** Service Collection */
  serviceCollection?: boolean | undefined;

  /** Related Services */
  relatedServices?: IService[] | undefined;
}

/** A service page */

export interface IService extends Entry<IServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "service";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowsFields {
  /** Title */
  title?: string | undefined;
  /** Introduction */
  introduction?: string | undefined;

shortBio?: | undefined;

  /** Content */
  content?: string | undefined;
  /** Show Banner*/
  showBanner?: string | undefined;
  playlistUrl?: string | undefined; 
  
  /**image */
  image?: Asset | undefined;

  /** Time Slots */
  timeSlots?: IShowSlot[] | undefined;

  /** Post Content */
  postContent: IPost;

  /** SEO */
  seo?: IMetatags | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path: string;

  /** Show URL */
  showUrl?: string | undefined;

  /** DJ */
  dj: IStaff[];

  /** tags */
  tags?: ITag[] | undefined;

  /** Components */
  components?: IComponent | undefined;


}

/** Scheduled radio shows for Waiheke Radio */

export interface IShows extends Entry<IShowsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "shows";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IShowSlotFields {
  /** Title */
  title?: string | undefined;

  /** Day */
  day:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday";

  /** Start Time */
  startTime: string;

  /** End Time */
  endTime: string;

  /** AM PM */
  amPm?: "AM" | "PM" | undefined;
}

/** A day / time range object for show scheduling */

export interface IShowSlot extends Entry<IShowSlotFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "showSlot";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStaffFields {
  /** Title */
  title?: string | undefined;

  /** First name */
  first_name: string;

  /** Last name */
  last_name?: string | undefined;

  /** Photo */
  photo?: Asset | undefined;

  /** Bio */
  bio?: Document | undefined;

  /** ShortBio */
  shortBio?: string | undefined;

  /** slug */
  slug?: string | undefined;

  /** path */
  path?: string | undefined;
}

/** An entity to contain staff and authors */

export interface IStaff extends Entry<IStaffFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "staff";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStreamFields {
  /** Title */
  title?: string | undefined;

  /** url */
  url?: string | undefined;

  /** Playing Now */
  playingNow?: string | undefined;
}

export interface IStream extends Entry<IStreamFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "stream";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagFields {
  /** Tag Name */
  tagName: string;
}

/** A single field tag item for categorisation */

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tag";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** Image */
  image?: Asset | undefined;

  /** Title */
  title?: string | undefined;

  /** Introduction */
  introduction?: string | undefined;

  /** Watch Message */
  watchMessage?: string | undefined;

  /** Youtube ID */
  youtubeId?: string | undefined;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "banner"
  | "blog"
  | "collection"
  | "color"
  | "component"
  | "config"
  | "events"
  | "footer"
  | "headerConfiguration"
  | "landingPage"
  | "linkedIcon"
  | "menu"
  | "message"
  | "metatags"
  | "navigationLink"
  | "partner"
  | "podcast"
  | "post"
  | "schedule"
  | "service"
  | "shows"
  | "showSlot"
  | "staff"
  | "stream"
  | "tag"
  | "video";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
